# This rule is not used by the project sp-template itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over services.openmcp.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sp-template
    app.kubernetes.io/managed-by: kustomize
  name: fooservice-admin-role
rules:
- apiGroups:
  - services.openmcp.cloud
  resources:
  - fooservices
  verbs:
  - '*'
- apiGroups:
  - services.openmcp.cloud
  resources:
  - fooservices/status
  verbs:
  - get
