# This rule is not used by the project sp-template itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the services.openmcp.cloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sp-template
    app.kubernetes.io/managed-by: kustomize
  name: fooservice-editor-role
rules:
- apiGroups:
  - services.openmcp.cloud
  resources:
  - fooservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.openmcp.cloud
  resources:
  - fooservices/status
  verbs:
  - get
