apiVersion: foo.services.openmcp.cloud/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    app.kubernetes.io/name: sp-template
    app.kubernetes.io/managed-by: kustomize
  name: providerconfig-sample
spec:
  # TODO(user): Add fields here
